# Generated by Django 6.0.2 on 2026-03-03 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Obrazek')),
                ('content', models.TextField(verbose_name='Treść')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publikacji')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Autor')),
                ('tag', models.CharField(choices=[('ogolne', 'Ogólne'), ('naxiom', 'nAxiom'), ('sql', 'SQL')], default='ogolne', max_length=20)),
            ],
            options={
                'verbose_name': 'Wpis',
                'verbose_name_plural': 'Wpisy',
            },
        ),
    ]
