# Generated by Django 6.0.2 on 2026-02-25 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publikacji')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Wpis',
                'verbose_name_plural': 'Wpisy',
            },
        ),
    ]
