# Generated by Django 6.0.2 on 2026-03-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('ogolne', 'Ogólne'), ('naxiom', 'nAxiom'), ('sql', 'SQL')], default='ogolne', max_length=20),
        ),
    ]
