# Generated by Django 6.0.2 on 2026-02-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa modułu')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność modułu')),
            ],
            options={
                'verbose_name': 'Moduł',
                'verbose_name_plural': 'Moduły',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł lekcji')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Treść lekcji')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność w module')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Moduł')),
            ],
            options={
                'verbose_name': 'Lekcja',
                'verbose_name_plural': 'Lekcje',
                'ordering': ['order'],
            },
        ),
    ]
